name-template: 'name-template v$RESOLVED_VERSION'
tag-template: 'tag-template v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'fix'
  default: patch

template: |
  ## Changes

  $CHANGES
