name: Pushes to Master

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/10 * * * *'

jobs:
  default:
    name: Default job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "on pushes to master"
