name: Pushes to Master

on:
  push:
    branches:
      - master
#  schedule:
#    - cron: '*/10 * * * *'

jobs:
  default:
    name: Default job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "on pushes to master"

  publish:
    needs:
      - default
    name: Publish to Test PYPI
    runs-on: ubuntu-latest
    env:
      POETRY_REPOSITORIES_TESTPYPI_URL: "https://test.pypi.org/legacy/"
      POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.TEST_PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install poetry
      - name: Build and publish to Test PYPI
        run: poetry publish --dry-run --build -r testpypi
