name: Pull-requests to Parallel

on:
  push:
    branches:
      - parallel
  pull_request:
    branches:
      - parallel

jobs:
  default:
    name: Default job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "on pull requests to parallel"
