name: Pull-requests to Master

on:
  pull_request:
    branches:
      - master

jobs:
  default:
    name: Default job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: |
          echo "on pull requests to master"
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
