name: Pull-requests to Master

on:
  pull_request:
    branches:
      - master

jobs:
  default:
    name: Default job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "on pull requests to master"
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git@10
            @semantic-release/changelog@6
            @semantic-release/exec@6
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
